apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-service
spec:
  selector:
    app: simple-node-app #which pod's key value is same
  type: LoadBalancer #it will create a load balancer for the service
  ports:
    - protocol: TCP
      port: 7000 #port of the service
      targetPort: 5000 #port of the container
      # nodePort: 30002 #port of the node , khidki kholi on node at port 30001 iss khidki se koi v andar aa skta h node k andar aur service isko target port pe redirect krega
